name: Update Contributors

on:
  pull_request:
    types: [opened, closed]

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run All Contributors Bot
        run: |
          npx all-contributors add ${GITHUB_ACTOR} code
          npx all-contributors generate
